server/main/urls.py
from django.urls import path

from .views import (
    index, contacts, about
)


app_name = 'main'


urlpatterns = [
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('', index, name='index'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('categories/', include('products.urls.categories')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

server/main/models.py
from django.db import models

# Create your models here.

server/main/views.py
from django.shortcuts import render
from django.template import Template, Context
from django.utils.html import mark_safe
from django.template.loader import get_template, render_to_string
from django.http import HttpResponse


# Create your views here.
def index(request):
    # CONST = False

    # template = Template('<h1>{{ variable }}</h1>')

    # if CONST:
    #     context_value = {'variable':'Hello'} 
    # else:
    #     context_value = {'variable':'World'}

    # context = Context(context_value)

    # return HttpResponse(
    #     template.render(context)
    # )
    template = get_template('main/index.html')
    context = {
        'description': 'Главная страница Интернет-витрины',
        'request': request
    }
    return HttpResponse(
        template.render(context)
    )


def about(request):
    return HttpResponse(
        render_to_string(
            'main/about.html',
            {
                'description': 'Информационная страница Интернет-витрины',
                'request': request
            }
        )
    )


def contacts(request):
    return render(
        request, 
        'main/contacts.html',
        {
            'contacts': [
                'Контакт1','Контакт2','Контакт3',
            ]
        }
    )

server/main/templates/main/about.html
{% extends 'main/master.html' %}

{% block page_title %}
About page
{% endblock %}

{% block page_content %}
    <div class="page__content">
        <h1 class="page__title">
            О проекте
        </h1>
        <div class="branding">
            <img src="" alt="" class="branding__background">
            <span class="branding__snippet">
                {{ description }}
            </span>
        </div>
    </div>
{% endblock %}

server/main/templates/main/contacts.html
{% extends 'main/master.html' %}

{% block page_title %}
Contacts page
{% endblock %}

{% block page_content %}
    <div class="page__content">
        <h1 class="page__title">
            Контакты
        </h1>
        <ul class="contacts-list">
            {% for itm in contacts %}
            <li>
                <span>
                    {{ itm }}
                </span>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

server/main/templates/main/index.html
{% extends 'main/master.html' %}

{% block page_title %}
Home page
{% endblock %}

{% block page_content %}
    <div class="page__content">
        <h1 class="page__title">
            Главная страница
        </h1>
        <div class="page__preview">
            <img src="" alt="" class="branding__background">
            <span class="branding__snippet">
                {{ description }}
            </span>
        </div>
    </div>
{% endblock %}

server/main/templates/main/master.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block page_title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" media="screen" href="/static/main/css/index.css" />
    </head>

    <body>
        <div class="page">
            <header class="page__header">
                <nav class="page__navigation">
                    <ul class="navigation-list">
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Главная
                            </span>
                            <a href="{% url 'main:index' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Продукты
                            </span>
                            <a href="{% url 'products:index' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                О проекте
                            </span>
                            <a href="/about/" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Контакты
                            </span>
                            <a href="/contacts/" class="navigation-list__item-link">
                            </a>
                        </li>
                    </ul>
                </nav>
            </header>

            <h3 class="user-name">
                <span>
                    {{ request.user }}
                </span>
            </h3>

            {% block page_content %}
            {% endblock %}

            <footer class="page__footer">
                <span class="page__copyright">
                    © GeekBrains
                </span>
            </footer>
        </div>
    </body>
</html>